const API = `${location.origin}/api`;
const $ = s => document.querySelector(s);
let skills = [];
let voiceSettings = {browser_fallback: false};
let activeRecorder = null;
let activeStream = null;
let recordedChunks = [];
const voiceApprovalIds = new Set();
let activeRequestSocket=null;
let activeRequestId=null;
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderMetrics(items){if(!items.length)return;const root=$('#metrics');root.replaceChildren();for(const m of items){const card=document.createElement('article');card.className='card';const title=document.createElement('div');title.className='card-label';title.textContent=m.name;const content=document.createElement('p');content.style.cssText='white-space:pre-wrap;font-size:11px;line-height:1.5;margin-top:12px';content.textContent=m.content;const path=document.createElement('small');path.textContent=m.path;card.append(title,content,path);root.append(card)}}
async function load(){try{const [status,catalog,metrics,pending]=await Promise.all([fetch(`${API}/status`).then(r=>r.json()),fetch(`${API}/skills`).then(r=>r.json()),fetch(`${API}/metrics`).then(r=>r.json()),fetch(`${API}/approvals`).then(r=>r.json())]);skills=catalog;voiceSettings=status.voice||voiceSettings;$('#voice-label').textContent=`Whisper: ${voiceSettings.stt} · Kokoro: ${voiceSettings.tts}`;$('#voice-vital').textContent=voiceSettings.stt==='ready'&&voiceSettings.tts==='ready'?'Local ready':'Setup needed';$('#voice-detail').textContent=`Whisper ${voiceSettings.stt} · Kokoro ${voiceSettings.tts}`;$('#skill-count').textContent=status.skills;$('#backend-label').textContent=status.backend==='claude'?'Claude Code':'Codex';$('#backend').value=status.backend;$('#vault-label').textContent='Connected';const root=$('#skills');root.replaceChildren();for(const s of catalog){const card=document.createElement('article');card.className='card skill';const domain=document.createElement('span');domain.className='domain';domain.textContent=s.domain;const name=document.createElement('strong');name.textContent=s.name;const desc=document.createElement('small');desc.textContent=s.description;const count=document.createElement('small');count.style.cssText='margin:9px 0;color:#f4cb75';count.textContent=`${s.successful_runs||0}/5 user-confirmed successful runs`;const gate=document.createElement('small');gate.textContent=s.approval_required?'Per-run approval required: sends / spends / publishes':'No per-run external-action gate';const run=document.createElement('button');run.className='ghost';run.textContent='Run skill';run.onclick=()=>submit('',s.id);card.append(domain,name,desc,count,gate,run);const promotion=document.createElement('button');promotion.className='ghost';promotion.style.marginTop='8px';promotion.textContent=s.promotion_status==='approved'?'Automation approved':s.promotion_status==='pending_review'?'Approve promotion?':'Promote to automation?';promotion.disabled=(s.promotion_status==='not_started'&&(s.successful_runs||0)<5)||s.promotion_status==='approved';promotion.onclick=async()=>{const action=s.promotion_status==='pending_review'?'promote/approve':'promote';const response=await fetch(`${API}/skills/${encodeURIComponent(s.id)}/${action}`,{method:'POST'});const data=await response.json();if(!response.ok){addTerm(data.detail||'Promotion review failed');return}addTerm(action==='promote'?'Automation review requested.':'Automation promotion approved.');load()};card.append(promotion);root.append(card)}renderMetrics(metrics);renderPendingApprovals(pending)}catch(e){$('#state').textContent='BRIDGE OFFLINE';addTerm('Bridge unavailable. Start `python -m cortexos serve` on this machine.')}}
function renderPendingApprovals(items){const root=$('#pending-approvals');if(!root)return;root.replaceChildren();if(!items.length){const empty=document.createElement('article');empty.className='card';empty.textContent='No pending approvals.';root.append(empty);return}for(const item of items){const card=document.createElement('article');card.className='card';const prompt=document.createElement('p');prompt.textContent=`${item.skill||'Request'} · ${item.prompt}`;const button=document.createElement('button');button.className='ghost';button.textContent='Approve and run';button.onclick=()=>approve(item.id);card.append(prompt,button);root.append(card)}}
function addTerm(text){const p=document.createElement('p');p.textContent=`[${new Date().toLocaleTimeString()}] ${text}`;$('#term-body').append(p);$('#term-body').scrollTop=$('#term-body').scrollHeight}
async function submit(prompt=$('#prompt').value,skill_id=null,speak=false){if(!prompt&&!skill_id)return;const backend=$('#backend').value;$('#state').textContent='WORKING';$('#run').disabled=true;addTerm(`Request: ${skill_id||prompt}`);try{const request_id=crypto.randomUUID();const res=await fetch(`${API}/requests`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:prompt||`Run skill ${skill_id}`,skill_id,backend,background:true,request_id})}).then(r=>r.json());if(res.status==='running')watchRequest(res.id,speak);else showResult(res,speak)}catch(e){addTerm(`Error: ${e.message}`);$('#state').textContent='ERROR'}finally{$('#run').disabled=false;$('#prompt').value='';if($('#state').textContent==='WORKING')$('#state').textContent='IDLE'}}
async function approve(id){$('#state').textContent='WORKING';addTerm('Approval received. Executing…');const response=await fetch(`${API}/requests/${id}/approve?background=true`,{method:'POST'});const res=await response.json();if(res.status==='running')watchRequest(id,voiceApprovalIds.delete(id));else showResult(res,voiceApprovalIds.delete(id));}
function showApproval(data,shouldSpeak=false){if(shouldSpeak)voiceApprovalIds.add(data.id);$('#result').textContent='This request may send, spend, or publish. Approve explicitly before CortexOS continues.';const button=document.createElement('button');button.className='ghost';button.textContent='Approve and run';button.onclick=()=>approve(data.id);$('#result').append(button);$('#state').textContent='IDLE';if(shouldSpeak)speakText('This request needs your approval before it can continue.')}
function showResult(res,shouldSpeak=false){if(res.status==='awaiting_approval'){showApproval(res,shouldSpeak);return}if(res.result){$('#result').textContent=res.result;const controls=document.createElement('div');controls.className='approval';const speak=document.createElement('button');speak.textContent='Speak with local Kokoro';speak.onclick=()=>speakText(res.result);controls.append(speak);if(res.skill){const yes=document.createElement('button');yes.textContent='Mark successful run';yes.onclick=()=>feedback(res,true);const no=document.createElement('button');no.textContent='Needs improvement';no.style.cssText='background:#35414d;color:#e5edf3';no.onclick=()=>feedback(res,false);controls.append(yes,no)}$('#result').append(controls);addTerm(`Completed · tier ${res.tier} · saved ${res.output}`);$('#state').textContent='IDLE';if(shouldSpeak)speakText(res.result);load()}else{ $('#result').textContent=res.error||JSON.stringify(res);$('#state').textContent='ERROR';addTerm(res.error||'Request failed')}}
function watchRequest(id,shouldSpeak=false){activeRequestId=id;$('#state').textContent='WORKING';$('#task-stream').style.display='block';$('#task-output').textContent='';$('#task-state').textContent='WORKING';$('#skill-interrupt').disabled=false;const proto=location.protocol==='https:'?'wss:':'ws:';activeRequestSocket=new WebSocket(`${proto}//${location.host}/api/requests/${id}/stream`);activeRequestSocket.onopen=()=>$('#state').textContent='WORKING';activeRequestSocket.onmessage=event=>{const message=JSON.parse(event.data);if(message.type==='output'||message.type==='notice'){$('#task-output').textContent+=message.data||`${message.text}\n`;$('#task-output').scrollTop=$('#task-output').scrollHeight}else if(message.type==='done'){$('#task-state').textContent=message.result?.status||'DONE';$('#skill-interrupt').disabled=true;showResult(message.result||{status:'error',error:'Request ended without a result'},shouldSpeak);activeRequestId=null}};activeRequestSocket.onerror=()=>{$('#task-state').textContent='STREAM ERROR';$('#skill-interrupt').disabled=true;$('#state').textContent='ERROR'};activeRequestSocket.onclose=()=>{if(activeRequestId===id){activeRequestId=null;$('#skill-interrupt').disabled=true;$('#state').textContent='IDLE'}}}
async function feedback(res,useful){await fetch(`${API}/requests/${res.id}/feedback`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({skill_id:res.skill,useful})});addTerm(useful?'Run recorded as successful.':'Run marked for improvement.');load()}
$('#run').onclick=()=>submit();$('#prompt').addEventListener('keydown',e=>{if(e.key==='Enter')submit()});$('#refresh').onclick=load;$('#backend').onchange=()=>$('#backend-label').textContent=$('#backend').value==='claude'?'Claude Code':'Codex';document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));n.classList.add('active');$('#page-title').textContent=n.dataset.tab});
function base64Of(blob){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',',2)[1]);reader.onerror=reject;reader.readAsDataURL(blob)})}
function appendBrowserFallback(container,kind,detail){const note=document.createElement('p');note.textContent=detail;container.append(note);if(!voiceSettings.browser_fallback)return;const button=document.createElement('button');button.className='ghost';button.style.marginTop='10px';button.textContent=kind==='stt'?'Last resort: browser speech recognition (may use an online service)':'Last resort: browser/system speech (may use an online service)';button.onclick=()=>kind==='stt'?browserFallbackSTT():browserFallbackTTS(container.dataset.speechText||'');container.append(button)}
async function localVoiceTurn(blob){$('#state').textContent='WORKING';addTerm('Transcribing locally with Whisper…');try{const encoded=await base64Of(blob);const response=await fetch(`${API}/voice/turn`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({audio_base64:encoded,content_type:blob.type||'audio/webm',backend:$('#backend').value,background:true,request_id:crypto.randomUUID()})});const data=await response.json();if(!response.ok)throw new Error(data.detail||'Local Whisper request failed');if(data.transcript)addTerm(`Whisper heard: ${data.transcript}`);if(data.status==='running')watchRequest(data.id,true);else showResult(data,true)}catch(e){$('#state').textContent='ERROR';addTerm(`Local Whisper unavailable: ${e.message}`);const result=$('#result');result.textContent=`Local voice could not process this recording. ${e.message}`;appendBrowserFallback(result,'stt','Your recording was not sent to browser speech recognition. Choose the fallback explicitly if you want to try it.')}}
async function toggleRecording(){if(activeRecorder&&activeRecorder.state==='recording'){activeRecorder.stop();$('#mic').textContent='◉';return}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){const result=$('#result');result.textContent='This environment cannot record audio for local Whisper.';appendBrowserFallback(result,'stt','Local recording is unavailable. Browser recognition is available only as an explicit last resort.');return}try{activeStream=await navigator.mediaDevices.getUserMedia({audio:true});recordedChunks=[];activeRecorder=new MediaRecorder(activeStream);activeRecorder.ondataavailable=e=>{if(e.data.size)recordedChunks.push(e.data)};activeRecorder.onstop=()=>{const blob=new Blob(recordedChunks,{type:activeRecorder.mimeType||'audio/webm'});activeStream.getTracks().forEach(t=>t.stop());activeStream=null;if(blob.size>20*1024*1024){$('#result').textContent='Recording exceeds the 20 MB limit.';return}localVoiceTurn(blob)};activeRecorder.start();$('#mic').textContent='■';$('#state').textContent='LISTENING';addTerm('Recording on this device. Press stop when finished.')}catch(e){$('#state').textContent='ERROR';addTerm(`Microphone permission failed: ${e.message}`)}}
function browserFallbackSTT(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){addTerm('This browser does not expose speech recognition.');return}const rec=new SR();rec.lang='en-US';rec.onstart=()=>{$('#state').textContent='LISTENING';addTerm('Browser fallback active. Audio may be processed by your browser or OS service.')} ;rec.onresult=e=>{const phrase=e.results[0][0].transcript;$('#prompt').value=phrase;$('#state').textContent='IDLE';submit(phrase,null,true)};rec.onerror=e=>{addTerm(`Browser fallback error: ${e.error}`);$('#state').textContent='ERROR'};rec.start()}
async function speakText(text){if(!text)return;$('#state').textContent='SPEAKING';try{const response=await fetch(`${API}/voice/speak`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:text.slice(0,5000)})});if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.detail||'Kokoro speech request failed')}const audio=new Audio(URL.createObjectURL(await response.blob()));audio.onended=()=>{$('#state').textContent='IDLE'};audio.onerror=()=>{$('#state').textContent='ERROR'};await audio.play()}catch(e){$('#state').textContent='IDLE';addTerm(`Local Kokoro unavailable: ${e.message}`);const result=$('#result');result.dataset.speechText=text;appendBrowserFallback(result,'tts',`Kokoro could not speak this response: ${e.message}`)}}
function browserFallbackTTS(text){if(!window.speechSynthesis){addTerm('Browser speech synthesis is unavailable.');return}const utterance=new SpeechSynthesisUtterance(text);utterance.onstart=()=>$('#state').textContent='SPEAKING';utterance.onend=()=>$('#state').textContent='IDLE';window.speechSynthesis.speak(utterance)}
$('#mic').onclick=toggleRecording;
$('#skill-interrupt').onclick=()=>{if(activeRequestSocket?.readyState===WebSocket.OPEN)activeRequestSocket.send(JSON.stringify({type:'interrupt'}))};
const panelNames={vitals:'Live vitals',skills:'Quick launch',metrics:'Your metrics',terminal:'Terminal',output:'Latest response',approvals:'Pending approvals'};
function readLayout(){try{return JSON.parse(localStorage.getItem('cortexos-layout')||'{}')}catch{return {}}}
function applyLayout(){const layout=readLayout(),main=document.querySelector('main');const panels=[...document.querySelectorAll('.panel')];panels.forEach(panel=>panel.hidden=!!layout.hidden?.includes(panel.dataset.panel));const order=layout.order||[];panels.sort((a,b)=>{const ai=order.indexOf(a.dataset.panel),bi=order.indexOf(b.dataset.panel);return (ai<0?999:ai)-(bi<0?999:bi)}).forEach(panel=>main.append(panel))}
function layoutEditor(){let editor=$('#layout-editor');if(editor){editor.remove();return}editor=document.createElement('div');editor.id='layout-editor';editor.innerHTML='<strong>Customize panels</strong><p class="dim">Reorder or hide panels on this device.</p>';const state=readLayout();const order=state.order||[];for(const panel of document.querySelectorAll('.panel')){const id=panel.dataset.panel,row=document.createElement('div');row.className='layout-row';const toggle=document.createElement('input');toggle.type='checkbox';toggle.checked=!(state.hidden||[]).includes(id);toggle.setAttribute('aria-label',`Show ${panelNames[id]}`);toggle.onchange=()=>{const current=readLayout(),hidden=new Set(current.hidden||[]);toggle.checked?hidden.delete(id):hidden.add(id);current.hidden=[...hidden];localStorage.setItem('cortexos-layout',JSON.stringify(current));applyLayout()};const label=document.createElement('span');label.textContent=panelNames[id]||id;const up=document.createElement('button');up.className='ghost';up.textContent='↑';const down=document.createElement('button');down.className='ghost';down.textContent='↓';const move=delta=>{const panels=[...document.querySelectorAll('.panel')].map(p=>p.dataset.panel);const index=panels.indexOf(id),target=index+delta;if(target<0||target>=panels.length)return;[panels[index],panels[target]]=[panels[target],panels[index]];const current=readLayout();current.order=panels;localStorage.setItem('cortexos-layout',JSON.stringify(current));applyLayout();layoutEditor()};up.onclick=()=>move(-1);down.onclick=()=>move(1);row.append(toggle,label,up,down);editor.append(row)}const close=document.createElement('button');close.className='ghost';close.textContent='Done';close.onclick=()=>editor.remove();editor.append(close);document.body.append(editor)}
$('#customize-layout').onclick=layoutEditor;applyLayout();
let activeTerminal=null;
let activeTerminalId=null;
$('#terminal-open').onclick=async()=>{if(!window.CortexTerminal){addTerm('Build the HUD terminal bundle with `cd apps/hud && npm install && npm run build`.');return}$('#terminal-open').disabled=true;try{const response=await fetch(`${API}/sessions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({backend:$('#terminal-backend').value,cols:100,rows:28})});const data=await response.json();if(!response.ok)throw new Error(data.detail||'Could not start terminal');activeTerminalId=data.id;const proto=location.protocol==='https:'?'wss:':'ws:';const url=`${proto}//${location.host}${data.websocket}`;$('#term-body').style.display='none';$('#xterm-container').style.display='block';activeTerminal=window.CortexTerminal.attach($('#xterm-container'),url,()=>{$('#terminal-interrupt').disabled=true});$('#terminal-interrupt').disabled=false;$('#terminal-close').disabled=false;addTerm(`${data.backend} interactive terminal started (${data.id})`)}catch(e){addTerm(`Terminal error: ${e.message}`);$('#terminal-open').disabled=false}};
$('#terminal-interrupt').onclick=()=>activeTerminal?.interrupt();
$('#terminal-close').onclick=async()=>{activeTerminal?.disconnect();if(activeTerminalId)await fetch(`${API}/sessions/${activeTerminalId}`,{method:'DELETE'});activeTerminal=null;activeTerminalId=null;$('#terminal-close').disabled=true;$('#terminal-interrupt').disabled=true;$('#terminal-open').disabled=false;$('#xterm-container').style.display='none';$('#term-body').style.display='block'};
load();setInterval(load,30000);
